version: '3'   
services:
  machine-learning:
    restart: always
    build: .
    container_name: 'machine-learning'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # command: /bin/bash