version: '3'   
services:
  machine-learning:
    restart: always
    build: .
    container_name: 'machine-learning'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt   # main component
      - /mnt0/Material-Management:/root/storage  # the directory has data
      - /etc/localtime:/etc/localtime:ro  #apply timezone(only Unix)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # command: /bin/bash