version: '3'   
services:
  machine-learning:
    restart: always
    build: .
    container_name: 'machine-learning'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt   # main component
      - ./list:/root/list   # moordinate list directory of items
      - ./trainImg:/root/trainImg   # the directory has train data 
      - ./target:/root/target   # the directory has target data for predict 
      - ./output:/root/output   # the directory willhave result 
      # - /etc/localtime:/etc/localtime:ro  #apply timezone(only Unix)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # command: /bin/bash